export const WEB_SAFE_FONTS = [
  'Roboto',
  'Arial',
  'Courier New',
  'Garamond',
  'Georgia',
  'Helvetica',
  'Tahoma',
  'Times New Roman',
  'Trebuchet MS',
  'Verdana',
];

export const WEB_SAFE_MONOSPACE_FONTS = [
  'Roboto Mono',
  'Consolas',
  'Courier New',
  'Lucida Console',
  'Monaco',
  'monospace',
];

export const SYNTAX_HIGHLIGHTER_THEMES = [
  { type: 'light', name: 'Base16 Ateliersulphurpool Light', value: 'base16AteliersulphurpoolLight', color: '#f5f7ff' },
  { type: 'light', name: 'Coldark Cold', value: 'coldarkCold', color: '#e3eaf2' },
  { type: 'light', name: 'Coy', value: 'coy', color: '#fdfdfd' },
  { type: 'light', name: 'Coy Without Shadows', value: 'coyWithoutShadows', color: '#fdfdfd' },
  { type: 'light', name: 'Duotone Light', value: 'duotoneLight', color: '#faf8f5' },
  { type: 'light', name: 'GHColors', value: 'ghcolors', color: '#ffffff' },
  { type: 'light', name: 'Gruvbox Light', value: 'gruvboxLight', color: '#f9f5d7' },
  { type: 'light', name: 'Material Light', value: 'materialLight', color: '#fafafa' },
  { type: 'light', name: 'One Light', value: 'oneLight', color: '#e6e6e5' },
  { type: 'light', name: 'Prism', value: 'prism', color: '#f5f2f0' },
  { type: 'light', name: 'Solarized Light', value: 'solarizedlight', color: '#fdf6e3' },
  { type: 'light', name: 'VS', value: 'vs', color: '#ffffff' },
  { type: 'dark', name: 'A11y Dark', value: 'a11yDark', color: '#2b2b2b' },
  { type: 'dark', name: 'Atom Dark', value: 'atomDark', color: '#1d1f21' },
  { type: 'dark', name: 'CB', value: 'cb', color: '#222222' },
  { type: 'dark', name: 'Coldark Dark', value: 'coldarkDark', color: '#111b27' },
  { type: 'dark', name: 'Darcula', value: 'darcula', color: '#2b2b2b' },
  { type: 'dark', name: 'Dark', value: 'dark', color: '#4d4033' },
  { type: 'dark', name: 'Dracula', value: 'dracula', color: '#282a36' },
  { type: 'dark', name: 'Duotone Dark', value: 'duotoneDark', color: '#2a2734' },
  { type: 'dark', name: 'Duotone Earth', value: 'duotoneEarth', color: '#322d29' },
  { type: 'dark', name: 'Duotone Forest', value: 'duotoneForest', color: '#2a2d2a' },
  { type: 'dark', name: 'Duotone Sea', value: 'duotoneSea', color: '#1d262f' },
  { type: 'dark', name: 'Duotone Space', value: 'duotoneSpace', color: '#24242e' },
  { type: 'dark', name: 'Funky', value: 'funky', color: '#1d1d1d' },
  { type: 'dark', name: 'Gruvbox Dark', value: 'gruvboxDark', color: '#1d2021' },
  { type: 'dark', name: 'Hopscotch', value: 'hopscotch', color: '#322931' },
  { type: 'dark', name: 'Lucario', value: 'lucario', color: '#263e52' },
  { type: 'dark', name: 'Material Dark', value: 'materialDark', color: '#2f2f2f' },
  { type: 'dark', name: 'Material Oceanic', value: 'materialOceanic', color: '#263238' },
  { type: 'dark', name: 'Night Owl', value: 'nightOwl', color: '#011627' },
  { type: 'dark', name: 'Nord', value: 'nord', color: '#2e3440' },
  { type: 'dark', name: 'Okaidia', value: 'okaidia', color: '#272822' },
  { type: 'dark', name: 'One Dark', value: 'oneDark', color: '#343028' },
  { type: 'dark', name: 'Pojoaque', value: 'pojoaque', color: '#18191d' },
  { type: 'dark', name: 'Solarized Dark Atom', value: 'solarizedDarkAtom', color: '#002b36' },
  { type: 'dark', name: 'Synthwave84', value: 'synthwave84', color: '#2a2139' },
  { type: 'dark', name: 'Tomorrow', value: 'tomorrow', color: '#2d2d2d' },
  { type: 'dark', name: 'Twilight', value: 'twilight', color: '#141414' },
  { type: 'dark', name: 'VS Dark Plus', value: 'vscDarkPlus', color: '#1e1e1e' },
  { type: 'dark', name: 'Xonokai', value: 'xonokai', color: '#2a2a2a' },
  { type: 'dark', name: 'Z Touch', value: 'zTouch', color: '#0a143c' },
];
