export const WEB_SAFE_FONTS = [
  'Roboto',
  'Arial',
  'Courier New',
  'Garamond',
  'Georgia',
  'Helvetica',
  'Tahoma',
  'Times New Roman',
  'Trebuchet MS',
  'Verdana',
];

export const WEB_SAFE_MONOSPACE_FONTS = [
  'Consolas',
  'Courier New',
  'Lucida Console',
  'Monaco',
  'monospace',
];

export const LIGHT_SYNTAX_HIGHLIGHTER_THEMES = [
  { name: 'Base16 Ateliersulphurpool Light', value: 'base16AteliersulphurpoolLight' },
  { name: 'Coldark Cold', value: 'coldarkCold' },
  { name: 'Coy', value: 'coy' },
  { name: 'Coy Without Shadows', value: 'coyWithoutShadows' },
  { name: 'Duotone Light', value: 'duotoneLight' },
  { name: 'GHColors', value: 'ghcolors' },
  { name: 'Gruvbox Light', value: 'gruvboxLight' },
  { name: 'Holi Theme', value: 'holiTheme' },
  { name: 'Material Light', value: 'materialLight' },
  { name: 'One Light', value: 'oneLight' },
  { name: 'Prism', value: 'prism' },
  { name: 'Shades Of Purple', value: 'shadesOfPurple' },
  { name: 'Solarized Light', value: 'solarizedlight' },
  { name: 'VS', value: 'vs' },
];

export const DARK_SYNTAX_HIGHLIGHTER_THEMES = [
  { name: 'A11y Dark', value: 'a11yDark' },
  { name: 'Atom Dark', value: 'atomDark' },
  { name: 'CB', value: 'cb' },
  { name: 'Coldark Dark', value: 'coldarkDark' },
  { name: 'Darcula', value: 'darcula' },
  { name: 'Dark', value: 'dark' },
  { name: 'Dracula', value: 'dracula' },
  { name: 'Duotone Dark', value: 'duotoneDark' },
  { name: 'Duotone Earth', value: 'duotoneEarth' },
  { name: 'Duotone Forest', value: 'duotoneForest' },
  { name: 'Duotone Sea', value: 'duotoneSea' },
  { name: 'Duotone Space', value: 'duotoneSpace' },
  { name: 'Funky', value: 'funky' },
  { name: 'Gruvbox Dark', value: 'gruvboxDark' },
  { name: 'Hopscotch', value: 'hopscotch' },
  { name: 'Lucario', value: 'lucario' },
  { name: 'Material Dark', value: 'materialDark' },
  { name: 'Material Oceanic', value: 'materialOceanic' },
  { name: 'Night Owl', value: 'nightOwl' },
  { name: 'Nord', value: 'nord' },
  { name: 'Okaidia', value: 'okaidia' },
  { name: 'One Dark', value: 'oneDark' },
  { name: 'Pojoaque', value: 'pojoaque' },
  { name: 'Solarized Dark Atom', value: 'solarizedDarkAtom' },
  { name: 'Synthwave84', value: 'synthwave84' },
  { name: 'Tomorrow', value: 'tomorrow' },
  { name: 'Twilight', value: 'twilight' },
  { name: 'VS Dark Plus', value: 'vscDarkPlus' },
  { name: 'Xonokai', value: 'xonokai' },
  { name: 'Z Touch', value: 'zTouch' },
];
