name: Run Lints

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run lint
  lint-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'packages/frontend/package.json'

      - name: Install dependencies
        working-directory: ./packages/frontend
        run: npm ci

      - name: Run tests
        working-directory: ./packages/frontend
        run: npm run lint