name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: 'package.json'

    - name: Install dependencies
      run: npm ci

    - name: Install dependencies
      working-directory: ./packages/frontend
      run: npm ci

    - name: Build package
      run: npm run build && npm run build:frontend

    - name: Run tests
      run: npm test

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
  test-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'packages/frontend/package.json'

      - name: Install dependencies
        working-directory: ./packages/frontend
        run: npm ci

      - name: Run tests
        working-directory: ./packages/frontend
        run: npm test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: frontend